package id.biojelan.app.ui.strings

/**
 * Implementasi BioStrings dalam Bahasa Indonesia.
 * Isi string persis sama dengan yang sekarang hardcoded di UI.
 */
object IdStrings : BioStrings {

    // ============================================================ Common
    override val appName = "BioJelan"
    override val reload = "Muat ulang"
    override val back = "Kembali"
    override val save = "Simpan"
    override val cancel = "Batalkan"
    override val accept = "Terima"
    override val close = "Tutup"
    override val total = "Total"
    override val or = "atau"

    // ============================================================ Auth
    override val welcomeTitle = "Selamat datang di BioJelan"
    override val welcomeSubtitle = "Tampilan akan menyesuaikan peran Anda"
    override val createAccountTitle = "Buat akun BioJelan"
    override val createAccountSubtitle = "Akun Anda terdaftar sebagai Klien. Untuk menjadi Agen, hubungi tim Kilang"
    override val signIn = "Masuk"
    override val signUp = "Daftar"
    override val forgotPasswordLink = "Lupa kata sandi?"
    override val forgotPasswordTitle = "Lupa kata sandi"
    override val forgotPasswordHeadline = "Kami kirim tautan reset ke email Anda"
    override val forgotPasswordBody = "Masukkan email yang terdaftar. Tautan untuk membuat kata sandi baru akan dikirim ke sana."
    override val sendResetLink = "Kirim tautan reset"
    override val resetSentNote = "Jika email terdaftar, tautan reset sudah dikirim. Cek kotak masuk (dan folder spam)."
    override val guestEntry = "Masuk sebagai tamu"
    override val retryButton = "Coba lagi"

    override val fieldFullName = "Nama lengkap"
    override val fieldEmail = "Email"
    override val fieldPassword = "Kata sandi"
    override val fieldRepeatPassword = "Ulangi kata sandi"
    override val placeholderName = "Nama Anda"
    override val placeholderEmail = "nama@email.com"
    override val placeholderPasswordMin = "Minimal 8 karakter"
    override val placeholderPasswordYours = "Kata sandi Anda"
    override val placeholderRepeatPassword = "Ketik ulang kata sandi"

    // ============================================================ Navigation tabs
    override val tabHome = "Beranda"
    override val tabFindAgent = "Cari Agen"
    override val tabTransactions = "Transaksi"
    override val tabStock = "Stok"
    override val tabPickup = "Pickup"
    override val pickupTitle = "Info Pickup"
    override val pickupIdLabel = "ID Pickup"
    override val pickupInfoUpdated = "Terakhir diperbarui"
    override val pickupInfoVolume = "Volume diminta Driver"
    override val pickupInfoVolumeValue = "dari lokasi Anda"
    override val pickupCancelledNote = "Penjemputan dibatalkan. Kilang akan menjadwalkan ulang bila diperlukan."
    override val pickupAwaitingYouNote = "Driver sudah mencatat pengambilan dan menunggu Anda menerima atau menolaknya."
    override val tabHistory = "Riwayat"
    override val tabProfile = "Profil"

    // ============================================================ Klien Home
    override val priceCaption = "Harga acuan Kilang"
    override val quickActionFindAgent = "Cari Agen"
    override val quickActionHistory = "Riwayat"
    override val quickActionMyId = "ID Saya"
    override val sectionAgenBioJelan = "Agen BioJelan"
    override val viewAll = "Lihat semua"
    override val noAgentsRegistered = "Belum ada Agen terdaftar."
    override val confirmTransaction = "Konfirmasi transaksi"
    override val open = "Buka"
    override val closed = "Tutup"
    override fun pendingTxBody(agenName: String, volume: String) =
        "$agenName mencatat penjualan $volume minyak jelantah atas nama Anda."

    // ============================================================ Agen Home
    override val priceCaptionAgen = "Harga acuan Kilang terkini"
    override val todayTransactions = "Transaksi hari ini"
    override val collectedToday = "Terkumpul hari ini"
    override val valueToday = "Nilai hari ini"
    override val currentStockLabel = "STOK SAAT INI"
    override val readyForPickup = "Siap dijemput Kilang"
    override fun remainingToThreshold(remaining: String) = "$remaining lagi menuju ambang"
    override val newTransaction = "Input Transaksi Baru"
    override val recentActivity = "Aktivitas terakhir"
    override val seeAll = "Semua"
    override val noTransactionsYet = "Belum ada transaksi."
    override val noTransactionsAgenHint = "Belum ada transaksi. Catat penjualan pertama dari Klien lewat tombol di atas."

    // ============================================================ Agen Stock
    override val stockTitle = "Stok"
    override fun thresholdCaption(threshold: String) = "dari ambang batas $threshold"
    override val aboveThresholdNote = "Stok sudah melewati ambang. Menunggu jadwal dari Kilang."
    override val stockThresholdInfo = "Setelah stok melewati ambang, Kilang akan menjadwalkan penjemputan. Ambang batas ditentukan oleh Kilang."
    override val stockMovement = "Pergerakan stok"
    override val noStockMovement = "Belum ada pergerakan. Stok bertambah saat Klien menerima transaksi."
    override val stockIncoming = "Masuk"
    override val stockWaiting = "Menunggu"
    override val stockCancelled = "Dibatalkan"
    override fun transactionDash(name: String) = "Transaksi — $name"

    // ============================================================ Agen Pickup
    override val pickupSectionTitle = "Status penjemputan"
    override val pickupNoneScheduled = "Belum ada penjemputan yang dijadwalkan Kilang."
    override val driverRequestsLoadFailed = "Permintaan Driver gagal dimuat, daftar di bawah mungkin belum terbaru."
    override val pickupStatusAssigned = "Driver ditugaskan"
    override val pickupStatusOtw = "Driver dalam perjalanan"
    override val pickupStatusCompleted = "Penjemputan selesai"
    override val pickupStatusCancelled = "Penjemputan dibatalkan"
    override val pickupNoteAssigned = "Kilang sudah menugaskan Driver. Siapkan dirigen Anda."
    override val pickupNoteOtw = "Driver sedang menuju lokasi Anda."
    override val pickupNoteCompleted = "Driver sudah mengambil minyak Anda. Kilang akan memperbarui stok."
    override fun pickupUpdatedAt(time: String) = "Diperbarui $time"

    // ============================================================ Agen Transactions
    override val transactionsTitle = "Transaksi"
    override val transactionDetailTitle = "Detail transaksi"
    override val todayLabel = "Hari ini"
    override val yesterdayLabel = "Kemarin"
    override val volumeToday = "Volume hari ini"
    override val noTransactionsTitle = "Belum ada transaksi"
    override val noTransactionsHint = "Tekan tombol + untuk mencatat penjualan dari Klien."
    override val transactionButton = "Transaksi"
    override val pendingAgenNote = "Menunggu Klien menerima atau menolak di app-nya."
    override val guestTxAgenNote = "Transaksi tamu dicatat offline. Tidak ada persetujuan Klien, jadi tidak bisa dibatalkan dari app."
    override val cancelledAgenNote = "Transaksi ini dibatalkan. Stok Anda tidak berubah."

    override val labelTransactionId = "ID Transaksi"
    override val labelDate = "Tanggal"
    override val labelAgent = "Agen"
    override val labelClient = "Klien"
    override val labelClientId = "ID Klien"
    override val labelVolume = "Volume"
    override val labelPricePerLiter = "Harga / liter"
    override val labelTotal = "Total"
    override val labelStatus = "Status"

    override val newTransactionTitle = "Input Transaksi Baru"
    override val newTransactionNote = "Masukkan email atau nomor telepon Klien yang terdaftar (Klien bisa melihatnya di menu \"ID Saya\"). Setelah dikirim, Klien akan diminta menerima atau menolak."
    override val txTabRegistered = "Klien Terdaftar"
    override val txTabGuest = "Tamu"
    override val fieldClientId = "ID Klien"
    override val fieldClientName = "Nama Klien"
    override val fieldVolume = "Volume minyak (liter)"
    override val fieldPricePerLiter = "Harga per liter"
    override val placeholderClientId = "ID dari app Klien"
    override val placeholderClientName = "Nama Klien"
    override val placeholderVolume = "mis. 12,5"
    override val hintReferencePriceKilang = "Harga acuan Kilang"
    override val submitToClient = "Kirim ke Klien"

    override val errorClientIdRequired = "ID Klien wajib diisi."
    override val errorClientNameRequired = "Nama Klien wajib diisi."
    override val errorVolumeRequired = "Masukkan volume lebih dari 0."
    override val errorVolumeTooLarge = "Volume terlalu besar — periksa kembali."

    // ============================================================ Klien History
    override val historyTitle = "Riwayat"
    override val transactionsCount = "Transaksi"
    override val oilSold = "Minyak terjual"
    override val totalReceived = "Total diterima"
    override val noHistoryTitle = "Belum ada transaksi"
    override val noHistoryHint = "Transaksi dengan Agen akan muncul di sini."
    override val pendingKlienNote = "Periksa jumlah dan harga. Terima jika sudah sesuai dengan yang Anda serahkan ke Agen; tolak jika tidak."
    override val cancelNotUndoable = "Pembatalan tidak dapat diurungkan."
    override val yesCancel = "Ya, batalkan"
    override val reject = "Tolak"
    override val yesReject = "Ya, tolak"
    override val rejectNotUndoable = "Penolakan tidak dapat diurungkan."
    override val cancelRequestTitle = "Permintaan pembatalan"
    override fun cancelRequestBody(agenName: String, volume: String) =
        "$agenName meminta membatalkan transaksi $volume minyak jelantah."
    override val acceptCancel = "Setujui batal"
    override val rejectCancel = "Tolak batal"
    override val cancelRequestedKlienNote = "Agen meminta transaksi ini dibatalkan. Setujui jika memang batal; tolak jika transaksi tetap berlaku."
    override val requestCancel = "Ajukan pembatalan"
    override val yesRequestCancel = "Ya, ajukan"
    override val cancelRequestedAgenNote = "Pembatalan sudah diajukan. Menunggu Klien menyetujui atau menolak."
    override val rejectedAgenNote = "Klien menolak transaksi ini. Stok Anda tidak berubah."
    override val fieldClientContact = "Email atau No. Telepon Klien"
    override val placeholderClientContact = "email@contoh.com atau 0812…"
    override val errorClientContactRequired = "Email atau nomor telepon Klien wajib diisi."
    override val roleDriver = "Driver"
    override val labelIdDriver = "ID Driver"
    override val driverRequestTitle = "Permintaan Driver"
    override fun driverRequestBody(volume: String) = "Driver ingin mengambil $volume minyak jelantah dari Anda."
    override fun driverCancelBody(volume: String) = "Driver meminta membatalkan pengambilan $volume minyak jelantah."
    override val driverNewTransactionTitle = "Catat Pengambilan"
    override val driverNewTransactionNote = "Masukkan email atau nomor telepon Agen yang terdaftar. Agen akan diminta menerima atau menolak; harga dihitung server."
    override val fieldAgenContact = "Email atau No. Telepon Agen"
    override val placeholderAgenContact = "email@contoh.com atau 0812…"
    override val errorAgenContactRequired = "Email atau nomor telepon Agen wajib diisi."
    override val fieldTransactionNote = "Catatan (opsional)"
    override val placeholderTransactionNote = "mis. diambil sore ini"
    override val submitToAgen = "Kirim ke Agen"
    override val driverNoTransactionsHint = "Tekan tombol + untuk mencatat pengambilan dari Agen."
    override val labelNote = "Catatan"
    override val pendingDriverNote = "Menunggu Agen menerima atau menolak permintaan ini."
    override val rejectedDriverNote = "Agen menolak permintaan ini."
    override val cancelRequestedDriverNote = "Pembatalan sudah diajukan. Menunggu Agen menyetujui atau menolak."
    override val cancelledDriverNote = "Transaksi ini dibatalkan."
    override val driverStockSection = "Pengambilan oleh Driver"
    override val driverStockRow = "Pengambilan Driver"
    override val stockOutgoing = "Keluar"
    override val driverPickupSection = "Penjemputan hari ini"
    override val driverIdleTitle = "Siap menerima penugasan"
    override val driverIdleLive = "Memantau penugasan"
    override val driverRecordButton = "Catat pengambilan"
    override val driverIdleHistory = "Riwayat"
    override val tabRouteHistory = "Riwayat"
    override val routeHistoryTitle = "Riwayat Rute"
    override fun routeHistoryItem(date: String) = "Rute $date"
    override val routeHistoryAgenLabel = "Agen"
    override val routeHistoryCollectedLabel = "terkumpul"
    override val routeHistorySpanLabel = "rentang"
    override fun routeHistoryAwaiting(count: Int) = "$count menunggu Agen"
    override val routeHistoryNote = "Rute dihitung per hari dari transaksi pengambilan Anda. Ketuk kartu untuk melihat daftar kunjungan."
    override val routeHistoryEmptyTitle = "Belum ada riwayat rute"
    override val routeHistoryEmptyHint = "Rute yang sudah Anda jalani akan muncul di sini setelah ada pengambilan yang dicatat."
    override val driverPickupAssigned = "Anda ditugaskan"
    override val driverPickupNoteAssigned = "Kilang menugaskan Anda menjemput minyak dari Agen. Mulai perjalanan saat berangkat."
    override val driverPickupOtw = "Dalam perjalanan"
    override val driverPickupNoteOtw = "Tandai selesai setelah minyak diambil dari Agen."
    override val driverPickupCompleted = "Penjemputan selesai"
    override val driverPickupNoteCompleted = "Catat volume yang diambil lewat tab Transaksi."
    override val driverPickupCancelled = "Penjemputan dibatalkan"
    override val driverPickupStart = "Mulai jalan"
    override val driverPickupFinish = "Selesai"
    override val driverPickupArrived = "Sudah tiba di lokasi"
    override val driverPickupNoteArrived = "Catat transaksi pengambilan lewat tab Transaksi, lalu tandai selesai."
    override val driverPickupArrive = "Saya sudah tiba"
    override val pickupStatusArrived = "Driver tiba di lokasi"
    override val pickupNoteArrived = "Driver sudah sampai. Timbang dan catat serah terima minyak."
    override val routeToAgen = "Rute ke Agen"
    override val driverGpsBadge = "Setiap Anda memperbarui status, checkpoint langsung terkirim ke Kilang."
    override val driverRouteToday = "Rute hari ini"
    override val driverEstVolume = "Est. volume"
    override val driverVisitOrder = "Urutan kunjungan"
    override val driverNewTaskTitle = "Tugas baru ditugaskan"
    override fun driverNewTaskBody(id: String, agen: String) = "Rute $id · $agen"
    override fun driverRouteHeadline(count: Int) = "Rute hari ini · $count Agen"
    override fun driverStopLabel(n: Int) = "Stop $n"
    override val stopChipWaiting = "Menunggu"
    override val stopChipDone = "Selesai"
    override val stopChipSkipped = "Dilewati"
    override val stopChipRejected = "Ditolak Agen"
    override val stopChipAwaitingAgen = "Menunggu Agen"
    override val stepAssigned = "Ditugaskan"
    override val stepOnTheWay = "Dalam perjalanan"
    override val stepArrived = "Tiba di lokasi"
    override val stepAwaiting = "Menunggu konfirmasi"
    override val stepCompleted = "Selesai"
    override val driverActionStart = "Mulai Perjalanan"
    override val driverActionArrive = "Saya Sudah Tiba"
    override val driverActionRecord = "Catat Pengambilan"
    override val driverActionAwaiting = "Menunggu Agen Konfirmasi..."
    override val driverActionDone = "Stop selesai"
    override val driverSkipLink = "Agen tutup atau tidak merespons, lewati stop ini"
    override val driverSkipTitle = "Lewati stop ini?"
    override val driverSkipBody = "Penugasan jemput ke Agen ini akan dibatalkan dan Kilang diberi tahu. Tindakan ini tidak bisa diurungkan."
    override val driverSkipConfirm = "Ya, lewati stop"
    override val driverAwaitingNote = "Permintaan pengambilan sudah dikirim. Agen perlu mengonfirmasinya di app."
    override val driverDoneNote = "Agen menerima permintaan. Volume dan pembayaran sudah tercatat."
    override val driverRejectedNote = "Agen menolak permintaan ini. Hubungi Agen atau Kilang bila perlu."
    override val driverStopAddress = "Alamat"
    override val driverStopHours = "Jam buka"
    override val driverStopVolume = "Volume tercatat"
    override val driverStopVolumeNone = "Belum dicatat"
    override val driverStopUnknownAgen = "Agen tujuan"
    override val driverCallAgen = "Hubungi Agen"
    override val driverOpenMaps = "Buka rute di Maps"
    override val driverNavigate = "Navigasi ke Agen"
    override val driverProgressTitle = "Posisi rute"
    override val driverProgressFrom = "Checkpoint terakhir"
    override val driverProgressTo = "Tujuan"
    override val driverProgressNone = "Belum ada"
    override val driverKilang = "Kilang"
    override val driverProgressReturn = "Kembali ke Kilang"
    override val driverNavigateSub = "Buka Google Maps. Rute dihitung dari posisimu sekarang."
    override val driverMapTapHint = "Ketuk untuk rute"
    override val driverMapHintBody = "Ketuk peta atau tombol Navigasi untuk buka Google Maps. Rute langsung jalan dari posisimu ke Agen."
    override val segmentClient = "Klien"
    override val segmentDriver = "Driver"
    override val agenDriverNoTransactionsHint = "Belum ada permintaan pengambilan dari Driver."
    override val labelDriver = "Driver"
    override val pendingDriverAgenNote = "Driver menunggu Anda menerima atau menolak permintaan ini. Stok Anda sudah dikurangi sejak permintaan ini dibuat."
    override val cancelRequestedDriverAgenNote = "Driver meminta membatalkan transaksi ini. Setujui jika memang batal; tolak jika transaksi tetap berlaku."
    override val rejectedDriverAgenNote = "Anda menolak permintaan ini. Stok yang sempat dikurangi saat Driver mengajukan sudah dikembalikan."
    override val cancelledDriverAgenNote = "Transaksi ini dibatalkan. Stok yang sempat dikurangi sudah dikembalikan."
    override val checkingClient = "Mengecek..."
    override fun clientFound(name: String) = "Klien ditemukan: $name"
    override val clientNotFound = "Klien belum terdaftar. Kirim tetap bisa dicoba, tapi biasanya ditolak server."

    // ============================================================ Guest
    override val guestBannerTitle = "Lihat sebagai tamu."
    override val guestBannerBody = "Daftar untuk mulai menjual minyak jelantah dan melihat riwayat transaksi Anda. Ketuk untuk mendaftar."
    override val guestPriceCaption = "Harga jelantah hari ini · berlaku untuk semua Agen"
    override val guestUpsellTitle = "Daftar untuk lanjut"
    override val guestUpsellBody = "Sebagai tamu, Anda hanya dapat melihat lokasi Agen di peta dan harga jelantah terkini. Daftar terlebih dahulu untuk mulai menjual minyak jelantah, melihat riwayat transaksi, dan mengatur profil."
    override val registerNow = "Daftar Sekarang"
    override val maybeLater = "Nanti dulu"

    // ============================================================ Profile
    override val profileTitle = "Profil"
    override val roleAgent = "Agen"
    override val roleClient = "Klien"
    override val sectionAccountData = "Data akun"
    override val sectionAgentData = "Data Agen"
    override val sectionSettings = "Pengaturan"
    override val verified = "Terverifikasi"
    override val statusActive = "Aktif"
    override val statusInactive = "Nonaktif"
    override val darkMode = "Mode gelap"
    override val darkModeHint = "Tampilan gelap untuk malam hari"
    override val liveAlertsTitle = "Pop-up notifikasi"
    override val liveAlertsHint = "Munculkan pemberitahuan saat ada yang baru"
    override val alertsOn = "Pop-up notifikasi aktif"
    override val alertsOff = "Pop-up notifikasi mati"
    override val notificationsTitle = "Notifikasi"
    override val notificationsEmpty = "Belum ada notifikasi"
    override val notificationsEmptyHint = "Transaksi atau permintaan baru yang masuk saat app terbuka akan muncul di sini."
    override val notificationsClear = "Hapus semua"
    override val labelPhone = "Telepon"
    override val labelIdAgent = "ID Agen"
    override val labelIdClient = "ID Klien"
    override val labelAddress = "Alamat"
    override val labelOperatingHours = "Jam operasional"
    override val labelBankAccount = "Rekening"
    override val labelStockThreshold = "Ambang stok"
    override val notFilled = "Belum diisi"
    override val setByKilang = "ditentukan Kilang"
    override val editProfile = "Ubah profil"
    override val changePassword = "Ubah kata sandi"
    override val logout = "Keluar"
    override val deleteAccount = "Hapus akun"

    override val editProfileTitle = "Ubah profil"
    override val fieldName = "Nama"
    override val fieldPhone = "Nomor telepon"
    override val fieldAddress = "Alamat"
    override val fieldBankName = "Nama bank"
    override val fieldAccountNumber = "Nomor rekening"
    override val fieldOpenTime = "Buka"
    override val fieldCloseTime = "Tutup"
    override val fieldOpenDays = "Hari buka"
    override val saveChanges = "Simpan perubahan"
    override val errorNameRequired = "Nama wajib diisi."
    override val errorTimeFormat = "Format HH:mm"
    override val placeholderPhone = "08xxxxxxxxxx"
    override val placeholderAddress = "Alamat lengkap"
    override val placeholderBankName = "mis. BCA"
    override val placeholderOpenTime = "08:00"
    override val placeholderCloseTime = "17:00"

    override val changePasswordTitle = "Ubah kata sandi"
    override val fieldCurrentPassword = "Kata sandi saat ini"
    override val fieldNewPassword = "Kata sandi baru"
    override val fieldRepeatNewPassword = "Ulangi kata sandi baru"
    override val hintMinChars = "Minimal 8 karakter"
    override val errorCurrentPasswordRequired = "Kata sandi saat ini wajib diisi."
    override val errorMinChars = "Minimal 8 karakter."
    override val errorConfirmMismatch = "Konfirmasi tidak cocok."
    override val savePassword = "Simpan kata sandi"

    override val deleteAccountTitle = "Hapus akun"
    override val deleteAccountWarning = "Akun beserta datanya akan dihapus permanen dan tidak bisa dipulihkan."
    override val deleteAccountConfirmLabel = "Ketik HAPUS untuk melanjutkan"
    override val deleteAccountConfirmWord = "HAPUS"
    override val deleteMyAccount = "Hapus akun saya"

    // ============================================================ Transaction status labels
    override fun txStatusLabel(status: String, isKlien: Boolean): String = when (status.trim().lowercase()) {
        "pending" -> if (isKlien) "Menunggu Anda" else "Menunggu Klien"
        "accepted" -> if (isKlien) "Selesai" else "Diterima"
        "rejected" -> if (isKlien) "Ditolak" else "Ditolak Klien"
        "cancel_requested" -> if (isKlien) "Pembatalan diajukan" else "Menunggu pembatalan"
        "cancelled", "canceled" -> "Dibatalkan"
        else -> "—"
    }
    override val statusCancelled = "Dibatalkan"

    // ============================================================ Greeting
    override fun greeting(hour: Int): String = when {
        hour < 11 -> "Selamat pagi"
        hour < 15 -> "Selamat siang"
        hour < 18 -> "Selamat sore"
        else -> "Selamat malam"
    }

    // ============================================================ Date/Time
    override fun relativeToday(time: String) = "Hari ini, $time"
    override fun relativeYesterday(time: String) = "Kemarin, $time"
    override val everyDay = "Setiap hari"
    override val hoursNotSet = "Jam belum diatur"
    override val timezone = "WIB"
    override val monthNames = listOf("Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des")

    // ============================================================ Errors
    override val networkError = "Tidak dapat terhubung ke server. Periksa koneksi internet Anda."
    override val sessionExpired = "Sesi Anda berakhir. Silakan masuk kembali."
    override fun serverError(code: Int) = "Terjadi kesalahan pada server ($code)."
    override val parseError = "Format data dari server tidak sesuai."

    // ============================================================ ID overlay
    override val myIdTitle = "ID Saya"
    override val defaultNickname = "Sobat BioJelan"
}